#!/usr/bin/env bash

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

# Install formulae
brew install tmux

# Remove outdated versions from cellar
brew cleanup
